### ISSUE TITLE
Introduce MFA Into Security Snap

### ISSUE THREAD

**Issue by wildwilliam2** [MythicLegendary/SP10_FALL_2022#12]

**Comment by wildwilliam2** [comment]
This is a feature we should implement given we have the time. Right now, we consider Cosmos integration the highest priority.

**Comment by wildwilliam2** [comment]
The time is right to implement new features in the backend. Ryan and Keving need to coordinate to implement about two features on the front and back end. Keving, try implementing this one, and contact William with ideas for other features.

**Comment by k3v1nw4ng** [comment]
Google authentication

**Comment by wildwilliam2** [comment]
I like that idea.

**Comment by wildwilliam2** [comment]
Implement MFA for the security snap.
Via the snap ui

or if possible

On the actual metamask application.

I understand the latter might not be possible; in that case write the code and we can port it over to the cosmos snap, to bloster its function.

**Comment by wildwilliam2** [comment]
Completing in cosmos-2fa

**Comment by wildwilliam2** [comment]
scratch  that
