### ISSUE TITLE
Create API Calling UI for Cosmos based on older index.html

### ISSUE THREAD

**Issue by wildwilliam2** [MythicLegendary/SP10_FALL_2022#19]

**Comment by AbhijayS** [comment]
I've created a general "card" UI constructor (see cosmos-snap/packages/site/src/components/Card.tsx) to easily create card UIs

**Comment by AbhijayS** [comment]
@wildwilliam2 All UI cards are complete. They all send the same 'hello' message to backend. Go ahead and close this task if complete.

**Comment by wildwilliam2** [comment]
I have integrated the changes into master.
Nice work.
Take a look at the modifications I made to snap.ts to get an idea of how I want new features to be implemented moving forward.
