### ISSUE TITLE
Implement 2FA Into Cosmos

### ISSUE THREAD

**Issue by AbhijayS** [MythicLegendary/SP10_FALL_2022#57]
Merge master, cosmos-ui, and security branches

**Comment by wildwilliam2** [comment]
Implementing firebase 2FA into Cosmos.

**Comment by wildwilliam2** [comment]
If the backend account is deleted by error, then the user cannot setup a wallet until the account is deleted in firebase

**Comment by wildwilliam2** [comment]
73a3f0c714579da358348017553fd4707d7e3864
